import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  index,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

/**
 * The seven account tables of specification section 12. Nothing else is
 * persisted: no heartbeats, no question/permission content, no terminal
 * events, no OpenCode conversation or source data.
 *
 * Conventions: uuid primary keys generated by the database, timezone-aware
 * timestamps, user-owned rows cascade on user deletion, and only token/key
 * hashes are stored (the spec never keeps raw secrets).
 */

const createdAt = () =>
  timestamp("created_at", { withTimezone: true }).notNull().defaultNow();

export const users = pgTable(
  "users",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // Stores the normalized address; the check rejects un-normalized writes
    // and the unique constraint enforces uniqueness after normalization.
    email: text("email").notNull().unique(),
    // Argon2id hash; the raw password never reaches the database.
    passwordHash: text("password_hash").notNull(),
    emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    check(
      "users_email_normalized",
      sql`${table.email} = lower(btrim(${table.email}))`,
    ),
  ],
);

export const emailVerificationTokens = pgTable("email_verification_tokens", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  tokenHash: text("token_hash").notNull().unique(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  consumedAt: timestamp("consumed_at", { withTimezone: true }),
  createdAt: createdAt(),
});

export const passwordResetTokens = pgTable("password_reset_tokens", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  tokenHash: text("token_hash").notNull().unique(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  consumedAt: timestamp("consumed_at", { withTimezone: true }),
  createdAt: createdAt(),
});

export const refreshTokenFamilies = pgTable("refresh_token_families", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  createdAt: createdAt(),
  // Set when reuse of a rotated token is detected or the password changes.
  revokedAt: timestamp("revoked_at", { withTimezone: true }),
});

export const refreshTokens = pgTable(
  "refresh_tokens",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    familyId: uuid("family_id")
      .notNull()
      .references(() => refreshTokenFamilies.id, { onDelete: "cascade" }),
    tokenHash: text("token_hash").notNull().unique(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    // Set on rotation; presenting an already-rotated token means reuse.
    rotatedAt: timestamp("rotated_at", { withTimezone: true }),
    createdAt: createdAt(),
  },
  (table) => [
    // Lookup path of the refresh flow: the not-yet-rotated token of a family.
    index("refresh_tokens_active_family_idx")
      .on(table.familyId)
      .where(sql`${table.rotatedAt} is null`),
  ],
);

export const devices = pgTable(
  "devices",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    platform: text("platform").notNull(),
    fcmToken: text("fcm_token"),
    enabled: boolean("enabled").notNull().default(true),
    soundEnabled: boolean("sound_enabled").notNull().default(true),
    createdAt: createdAt(),
    lastSeenAt: timestamp("last_seen_at", { withTimezone: true }),
  },
  (table) => [
    index("devices_user_idx").on(table.userId),
    check(
      "devices_platform_check",
      sql`${table.platform} in ('windows', 'linux', 'android')`,
    ),
  ],
);

export const ingestKeys = pgTable(
  "ingest_keys",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    // Public lookup id of the key (sent as the keyId credential).
    keyId: text("key_id").notNull().unique(),
    // Hash of the key secret; the secret is shown once at creation.
    secretHash: text("secret_hash").notNull(),
    name: text("name").notNull(),
    createdAt: createdAt(),
    lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
  },
  (table) => [
    // Listing a user's still-active keys (keyId lookups hit the unique index).
    index("ingest_keys_active_user_idx")
      .on(table.userId)
      .where(sql`${table.revokedAt} is null`),
  ],
);

/**
 * Operator accounts of the admin panel. Single-user deployments seed one
 * row from ADMIN_USERNAME/ADMIN_INITIAL_PASSWORD at startup; the password
 * is changed through the panel and only its Argon2id hash is stored.
 */
export const adminUsers = pgTable(
  "admin_users",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    username: text("username").notNull().unique(),
    // Argon2id hash; the raw password never reaches the database.
    passwordHash: text("password_hash").notNull(),
    createdAt: createdAt(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    check(
      "admin_users_username_normalized",
      sql`${table.username} = lower(btrim(${table.username}))`,
    ),
  ],
);

/**
 * Registration allowlist managed from the admin panel. `kind` is either
 * `domain` (the address must end with `@<value>`, e.g. nju.edu.cn) or
 * `email` (exact normalized match). The list gates only self-service
 * registration; the admin can always add accounts directly.
 */
export const registrationWhitelist = pgTable(
  "registration_whitelist",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    kind: text("kind").notNull(),
    value: text("value").notNull().unique(),
    createdAt: createdAt(),
  },
  (table) => [
    check(
      "registration_whitelist_kind_check",
      sql`${table.kind} in ('domain', 'email')`,
    ),
    check(
      "registration_whitelist_value_normalized",
      sql`${table.value} = lower(btrim(${table.value}))`,
    ),
  ],
);
