import { sql } from "drizzle-orm";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { buildServer } from "../../src/app.js";
import { createDb } from "../../src/db/client.js";
import { buildTestConfig } from "../helpers/build-test-app.js";
import { TestPostgres } from "../helpers/postgres.js";

/** The account tables of specification section 12 plus the admin tables, sorted. */
const ACCOUNT_TABLES = [
  "admin_users",
  "devices",
  "email_verification_tokens",
  "ingest_keys",
  "password_reset_tokens",
  "refresh_token_families",
  "refresh_tokens",
  "registration_whitelist",
  "users",
] as const;

async function tableNames(client: TestPostgres, schema: string): Promise<string[]> {
  const sqlClient = client.connect({ max: 1 });
  try {
    const rows = await sqlClient`
      select table_name from information_schema.tables
      where table_schema = ${schema} order by table_name
    `;
    return rows.map((row) => row.table_name as string);
  } finally {
    await client.release(sqlClient);
  }
}

describe("explicit database migrations", () => {
  let pg: TestPostgres;

  beforeAll(async () => {
    pg = await TestPostgres.start();
    await pg.migrate();
  });

  afterAll(async () => {
    await pg.stop();
  });

  it("creates exactly the account tables plus Drizzle's migration table", async () => {
    expect(await tableNames(pg, "public")).toEqual([...ACCOUNT_TABLES]);
    expect(await tableNames(pg, "drizzle")).toEqual(["__drizzle_migrations"]);
  });

  it("is idempotent: applying the migrations a second time changes nothing", async () => {
    const client = pg.connect({ max: 1 });
    try {
      const before = await client`
        select count(*)::int as n from drizzle.__drizzle_migrations
      `;
      const tablesBefore = await tableNames(pg, "public");
      expect(before[0].n).toBeGreaterThan(0);

      await pg.migrate();

      const after = await client`
        select count(*)::int as n from drizzle.__drizzle_migrations
      `;
      expect(after[0].n).toBe(before[0].n);
      expect(await tableNames(pg, "public")).toEqual(tablesBefore);
    } finally {
      await pg.release(client);
    }
  });

  it("gives every table a uuid primary key generated by the database", async () => {
    const client = pg.connect({ max: 1 });
    try {
      const rows = await client`
        select table_name, data_type, column_default
        from information_schema.columns
        where table_schema = 'public' and column_name = 'id'
        order by table_name
      `;
      expect(rows.map((row) => row.table_name)).toEqual([...ACCOUNT_TABLES]);
      for (const row of rows) {
        expect(row.data_type).toBe("uuid");
        expect(row.column_default).toBe("gen_random_uuid()");
      }
    } finally {
      await pg.release(client);
    }
  });

  it("stores every timestamp timezone-aware", async () => {
    const client = pg.connect({ max: 1 });
    try {
      const rows = await client`
        select table_name, column_name from information_schema.columns
        where table_schema = 'public'
          and data_type like 'timestamp%'
          and data_type <> 'timestamp with time zone'
      `;
      expect(rows).toEqual([]);
      const count = await client`
        select count(*)::int as n from information_schema.columns
        where table_schema = 'public' and data_type = 'timestamp with time zone'
      `;
      expect(count[0].n).toBeGreaterThan(0);
    } finally {
      await pg.release(client);
    }
  });

  it("enforces the unique constraints", async () => {
    const client = pg.connect({ max: 1 });
    try {
      const rows = await client`
        select tc.table_name, kcu.column_name
        from information_schema.table_constraints tc
        join information_schema.key_column_usage kcu
          on tc.constraint_name = kcu.constraint_name
         and tc.table_schema = kcu.table_schema
        where tc.table_schema = 'public' and tc.constraint_type = 'UNIQUE'
        order by tc.table_name, kcu.column_name
      `;
      const uniquePairs = rows.map((row) => `${row.table_name}(${row.column_name})`);
      expect(uniquePairs).toEqual(
        expect.arrayContaining([
          "users(email)",
          "email_verification_tokens(token_hash)",
          "password_reset_tokens(token_hash)",
          "refresh_tokens(token_hash)",
          "ingest_keys(key_id)",
        ]),
      );
    } finally {
      await pg.release(client);
    }
  });

  it("rejects non-normalized emails", async () => {
    const client = pg.connect({ max: 1 });
    try {
      const rows = await client`
        select conname, pg_get_constraintdef(oid) as def
        from pg_constraint
        where conrelid = 'public.users'::regclass and contype = 'c'
      `;
      const normalized = rows.find((row) => row.conname === "users_email_normalized");
      expect(normalized).toBeDefined();
      expect(normalized?.def).toContain("lower(");
    } finally {
      await pg.release(client);
    }
  });

  it("cascades every user-owned foreign key", async () => {
    const client = pg.connect({ max: 1 });
    try {
      const rows = await client`
        select tc.table_name, kcu.column_name, ccu.table_name as referenced_table,
               rc.delete_rule
        from information_schema.table_constraints tc
        join information_schema.key_column_usage kcu
          on tc.constraint_name = kcu.constraint_name
         and tc.table_schema = kcu.table_schema
        join information_schema.referential_constraints rc
          on tc.constraint_name = rc.constraint_name
         and tc.table_schema = rc.constraint_schema
        join information_schema.constraint_column_usage ccu
          on rc.unique_constraint_name = ccu.constraint_name
         and rc.unique_constraint_schema = ccu.constraint_schema
        where tc.table_schema = 'public' and tc.constraint_type = 'FOREIGN KEY'
        order by tc.table_name
      `;
      const fks = rows.map(
        (row) =>
          `${row.table_name}(${row.column_name})->${row.referenced_table}:${row.delete_rule}`,
      );
      expect(fks).toEqual([
        "devices(user_id)->users:CASCADE",
        "email_verification_tokens(user_id)->users:CASCADE",
        "ingest_keys(user_id)->users:CASCADE",
        "password_reset_tokens(user_id)->users:CASCADE",
        "refresh_token_families(user_id)->users:CASCADE",
        "refresh_tokens(family_id)->refresh_token_families:CASCADE",
      ]);
    } finally {
      await pg.release(client);
    }
  });

  it("creates the query indexes from the plan", async () => {
    const client = pg.connect({ max: 1 });
    try {
      const rows = await client`
        select indexname, tablename, indexdef from pg_indexes
        where schemaname = 'public'
      `;
      const byName = new Map(rows.map((row) => [row.indexname, row]));

      const devicesUser = byName.get("devices_user_idx");
      expect(devicesUser?.tablename).toBe("devices");
      expect(devicesUser?.indexdef).toContain("(user_id)");

      const activeRefresh = byName.get("refresh_tokens_active_family_idx");
      expect(activeRefresh?.tablename).toBe("refresh_tokens");
      expect(activeRefresh?.indexdef).toContain("(family_id)");
      expect(activeRefresh?.indexdef).toContain("WHERE (rotated_at IS NULL)");

      const activeIngest = byName.get("ingest_keys_active_user_idx");
      expect(activeIngest?.tablename).toBe("ingest_keys");
      expect(activeIngest?.indexdef).toContain("(user_id)");
      expect(activeIngest?.indexdef).toContain("WHERE (revoked_at IS NULL)");
    } finally {
      await pg.release(client);
    }
  });

  it("persists device flags enabled and soundEnabled with safe defaults", async () => {
    const client = pg.connect({ max: 1 });
    try {
      const rows = await client`
        select column_name, data_type, is_nullable, column_default
        from information_schema.columns
        where table_schema = 'public' and table_name = 'devices'
      `;
      const byName = new Map(rows.map((row) => [row.column_name, row]));

      const enabled = byName.get("enabled");
      expect(enabled?.data_type).toBe("boolean");
      expect(enabled?.is_nullable).toBe("NO");
      expect(enabled?.column_default).toBe("true");

      const soundEnabled = byName.get("sound_enabled");
      expect(soundEnabled?.data_type).toBe("boolean");
      expect(soundEnabled?.is_nullable).toBe("NO");
      expect(soundEnabled?.column_default).toBe("true");

      expect(byName.get("platform")?.is_nullable).toBe("NO");
      expect(byName.get("fcm_token")?.is_nullable).toBe("YES");
      expect(byName.has("last_seen_at")).toBe(true);
    } finally {
      await pg.release(client);
    }
  });

  it("createDb(databaseUrl) connects and closes cleanly", async () => {
    const { db, close } = createDb(pg.databaseUrl);
    const rows = await db.execute(sql`select 1 as one`);
    expect(rows[0].one).toBe(1);
    await close();
  });
});

describe("application startup", () => {
  it("never mutates the schema, even against an empty database", async () => {
    const pg = await TestPostgres.start();
    try {
      const app = await buildServer({
        config: buildTestConfig({ databaseUrl: pg.databaseUrl }),
      });
      try {
        const live = await app.inject({ method: "GET", url: "/health/live" });
        expect(live.statusCode).toBe(200);
        // Exercise the error paths too; nothing may touch the database.
        const missing = await app.inject({ method: "GET", url: "/missing" });
        expect(missing.statusCode).toBe(404);
      } finally {
        await app.close();
      }

      expect(await tableNames(pg, "public")).toEqual([]);
      const client = pg.connect({ max: 1 });
      try {
        const schemas = await client`
          select schema_name from information_schema.schemata
          where schema_name = 'drizzle'
        `;
        expect(schemas).toEqual([]);
      } finally {
        await pg.release(client);
      }
    } finally {
      await pg.stop();
    }
  });
});
